# Default values for tmleafnode.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: csp
subsystem: tmsimulator-mid
telescope: SKA-mid

globals:
  labels:
    app: mid-cbf-mcs
  annotations:
    app.gitlab.com/app: CI_PROJECT_PATH_SLUG
    app.gitlab.com/env: CI_ENVIRONMENT_SLUG
  tango_host: databaseds-tango-base-test:10000
  environment_variables: []
  dsconfig:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.5.0
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-itango
      tag: 9.3.1
      pullPolicy: IfNotPresent
dsconfig:
  configuration_file: data/tmleafnodeconfig.json

deviceServers:
  - name: tmcspsubarrayleafnodetest
    function: simul-observation
    domain: telstate
    args:
      - -c
      - "/venv/bin/python /app/tangods/TmCspSubarrayLeafNodeTest/TmCspSubarrayLeafNodeTest.py tm"
    depends_on:
      - device: mid_csp_cbf/sub_elt/subarray_01
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: mid-cbf-mcs
      tag: 0.4.5
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m     # 100m = 0.10 CPU
        memory: 128Mi # 128Mi = 0.12 GB mem
      limits:
        cpu: 200m     # 200m = 0.20 CPU
        memory: 256Mi # 256Mi = 0.25 GB mem
  - name: tmcspsubarrayleafnodetest2
    function: simul-observation
    domain: telstate
    args:
      - -c
      - "/venv/bin/python /app/tangods/TmCspSubarrayLeafNodeTest/TmCspSubarrayLeafNodeTest.py tm2"
    depends_on:
      - device: mid_csp_cbf/sub_elt/subarray_01
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: mid-cbf-mcs
      tag: 0.4.5
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m     # 100m = 0.10 CPU
        memory: 128Mi # 128Mi = 0.12 GB mem
      limits:
        cpu: 200m     # 200m = 0.20 CPU
        memory: 256Mi # 256Mi = 0.25 GB mem

nodeSelector: {}

tolerations: []

affinity: {}
