# Default values for tmleafnode.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: csp
subsystem: tmsimulator-mid
telescope: SKA-mid

labels:
  app: mid-cbf-tmleafnode
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000

dsconfig:
  configuration_file: data/tmleafnodeconfig.json
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-dsconfig
    tag: 1.5.0
    pullPolicy: IfNotPresent

itango:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-itango
    tag: 9.3.1
    pullPolicy: IfNotPresent


resources:
  limits:
    cpu: 200m
    memory: 256Mi
    ephemeral-storage: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi  
    ephemeral-storage: 256Mi

deviceServers:
  - name: tmcspsubarrayleafnodetest
    function: simul-observation
    domain: telstate
    command: "/venv/bin/python /app/tangods/TmCspSubarrayLeafNodeTest/TmCspSubarrayLeafNodeTest.py "
    instances: ["tm"]
    depends_on:
      - device: mid_csp_cbf/sub_elt/subarray_01
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: mid-cbf-mcs
      tag: 0.4.5
      pullPolicy: IfNotPresent
  - name: tmcspsubarrayleafnodetest2
    function: simul-observation
    domain: telstate
    command: "/venv/bin/python /app/tangods/TmCspSubarrayLeafNodeTest/TmCspSubarrayLeafNodeTest.py "
    instances: ["tm2"]
    depends_on:
      - device: mid_csp_cbf/sub_elt/subarray_02
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: mid-cbf-mcs
      tag: 0.4.5
      pullPolicy: IfNotPresent

nodeSelector: {}

tolerations: []

affinity: {}
