image: $SKA_K8S_TOOLS_BUILD_DEPLOY

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MINIKUBE: "false"
  SHARED_K8S_CHART: "ska-mid-cbf-mcs"

stages:
  - lint
  - build
  - test
  - deploy
  - integration
  - staging
  - join-reports
  - pages
  - publish
  - scan

# Include CI templates
include:
# OCI Images
# do a custom set of build and publish stages
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/oci-image.gitlab-ci.yml'

# Python packages build,lint, test and publish
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python.gitlab-ci.yml'

# Jupyter notebook linting and testing
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/notebook.gitlab-ci.yml'

# Helm Charts
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/helm-chart.gitlab-ci.yml'

# Docs pages
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs-pages.gitlab-ci.yml'

# .post step finalisers eg: badges
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

# k8s steps
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/k8s.gitlab-ci.yml'

# changelog release page
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/changelog.gitlab-ci.yml'

# deploy steps
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/deploy.gitlab-ci.yml'


helm-chart-lint:
  allow_failure: true

notebook-test:
  rules:
    - when: never

python-gemnasium-scan:
  rules:
    - when: never

deploy-dev-environment:
  variables:
    KUBE_NAMESPACE: "ci-dev-$CI_PROJECT_NAME-$CI_PIPELINE_ID"
  environment:
    name: ci-dev-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME

test-dev-environment:
  variables:
    KUBE_NAMESPACE: "ci-dev-$CI_PROJECT_NAME-$CI_PIPELINE_ID"
  environment:
    name: ci-dev-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME

info-dev-environment:
  variables:
    KUBE_NAMESPACE: "ci-dev-$CI_PROJECT_NAME-$CI_PIPELINE_ID"
  environment:
    name: ci-dev-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME

stop-dev-environment:
  variables:
    KUBE_NAMESPACE: "ci-dev-$CI_PROJECT_NAME-$CI_PIPELINE_ID"
  environment:
    name: ci-dev-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME

#### Override runner

default:
  tags:
    - aws-k8sruner

helm-chart-lint:
  tags:
    - aws-k8srunner

oci-image-lint:
  tags:
    - aws-k8srunner

python-lint:
  tags:
    - aws-k8srunner

helm-chart-build:
  tags:
    - aws-k8srunner

oci-image-build:
  tags:
    - aws-k8srunner

python-build-for-development:
  tags:
    - aws-k8srunner
  
k8s-test:
  tags:
    - aws-k8srunner

python-test:
  tags:
    - aws-k8srunner

stop-k8s-test:
  tags:
    - aws-k8srunner

docs-pages:
  tags:
    - aws-k8srunner

oci-image-scan:
  tags:
    - aws-k8srunner

python-gemnasium-scan:
  tags:
    - aws-k8srunner

python-publish-to-gitlab:
  tags:
    - aws-k8srunner

create-ci-metrics:
  tags:
    - aws-k8srunner

