version: '2'
volumes:
  tangodb: {}

services:
  vcc:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/csplmc:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}vcc
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             for i in $$(seq -w 1 197); do \
             tango_admin --check-device mid_csp_cbf/vcc/$$i ||\
             tango_admin --add-server Vcc/cbf Vcc mid_csp_cbf/vcc/$$i; done &&\
             /venv/bin/python /app/csplmc/Vcc/Vcc/Vcc.py cbf"

  fsp:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/csplmc:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}fsp
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             for i in $$(seq -w 1 27); do \
             tango_admin --check-device mid_csp_cbf/fsp/$$i ||\
             tango_admin --add-server Fsp/cbf Fsp mid_csp_cbf/fsp/$$i; done &&\
             /venv/bin/python /app/csplmc/Fsp/Fsp/Fsp.py cbf"

  cbfsubarray:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/csplmc:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cbfsubarray
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             for i in $$(seq -w 1 16); do \
             tango_admin --check-device mid_csp_cbf/cbfSubarray/$$i ||\
             tango_admin --add-server CbfSubarray/cbf CbfSubarray mid_csp_cbf/cbfSubarray/$$i; done &&\
             /venv/bin/python /app/csplmc/CbfSubarray/CbfSubarray/CbfSubarray.py cbf"

  cbfmaster:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/csplmc:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cbfmaster
    depends_on:
      - cbfsubarray
      - vcc
      - fsp
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --check-device mid_csp_cbf/master/main ||\
             tango_admin --add-server CbfMaster/cbf CbfMaster mid_csp_cbf/master/main &&\
             /venv/bin/python /app/csplmc/CbfMaster/CbfMaster/CbfMaster.py cbf"

