version: "2.2"

services:
  vcc:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/csplmc:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}vcc
    depends_on:
      - databaseds
      - rsyslog-csplmc
      - vcccapabilities
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             for i in $$(seq -w 1 197); do \
             tango_admin --check-device mid_csp_cbf/vcc/$$i; done &&\
             /venv/bin/python /app/csplmc/Vcc/Vcc/Vcc.py cbf"
             
  vcccapabilities:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/csplmc:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}vcccapabilities
    depends_on:
      - databaseds
      - rsyslog-csplmc
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             for i in $$(seq -w 1 197); do \
             tango_admin --check-device mid_csp_cbf/vcc_band12/$$i; done &&\
             /venv/bin/python /app/csplmc/Vcc/VccBand1And2/VccBand1And2.py cbf &\
             for i in $$(seq -w 1 197); do \
             tango_admin --check-device mid_csp_cbf/vcc_band3/$$i; done &&\
             /venv/bin/python /app/csplmc/Vcc/VccBand3/VccBand3.py cbf &\
             for i in $$(seq -w 1 197); do \
             tango_admin --check-device mid_csp_cbf/vcc_band4/$$i; done &&\
             /venv/bin/python /app/csplmc/Vcc/VccBand4/VccBand4.py cbf &\
             for i in $$(seq -w 1 197); do \
             tango_admin --check-device mid_csp_cbf/vcc_band5/$$i; done &&\
             /venv/bin/python /app/csplmc/Vcc/VccBand5/VccBand5.py cbf &\
             for i in $$(seq -w 1 197); do \
             tango_admin --check-device mid_csp_cbf/vcc_tdc1/$$i; done &&\
             for i in $$(seq -w 1 197); do \
             tango_admin --check-device mid_csp_cbf/vcc_tdc2/$$i; done &&\
             /venv/bin/python /app/csplmc/Vcc/VccTransientDataCapture/VccTransientDataCapture.py cbf"

  fsp:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/csplmc:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}fsp
    depends_on:
      - databaseds
      - rsyslog-csplmc
      - fspcapabilities
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             for i in $$(seq -w 1 27); do \
             tango_admin --check-device mid_csp_cbf/fsp/$$i; done &&\
             /venv/bin/python /app/csplmc/Fsp/Fsp/Fsp.py cbf"
             
  fspcapabilities:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/csplmc:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}fspcapabilities
    depends_on:
      - databaseds
      - rsyslog-csplmc
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             for i in $$(seq -w 1 27); do \
             tango_admin --check-device mid_csp_cbf/fsp_corr/$$i; done &&\
             /venv/bin/python /app/csplmc/Fsp/FspCorr/FspCorr.py cbf &\
             for i in $$(seq -w 1 27); do \
             tango_admin --check-device mid_csp_cbf/fsp_pss/$$i; done &&\
             /venv/bin/python /app/csplmc/Fsp/FspPss/FspPss.py cbf &\
             for i in $$(seq -w 1 27); do \
             tango_admin --check-device mid_csp_cbf/fsp_pst/$$i; done &&\
             /venv/bin/python /app/csplmc/Fsp/FspPst/FspPst.py cbf &\
             for i in $$(seq -w 1 27); do \
             tango_admin --check-device mid_csp_cbf/fsp_vlbi/$$i; done &&\
             /venv/bin/python /app/csplmc/Fsp/FspVlbi/FspVlbi.py cbf"
             
  fspsubarray:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/csplmc:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}fspsubarray
    depends_on:
      - databaseds
      - rsyslog-csplmc
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             for i in $$(seq -w 1 27); do \
             for j in $$(seq -w 1 16); do \
             tango_admin --check-device mid_csp_cbf/fspSubarray/$$i\_$$j; done; done &&\
             /venv/bin/python /app/csplmc/Fsp/FspSubarray/FspSubarray.py cbf"

  cbfsubarray:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/csplmc:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cbfsubarray
    depends_on:
      - vcc
      - fsp
      - databaseds
      - rsyslog-csplmc
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             for i in $$(seq -w 1 16); do \
             tango_admin --check-device mid_csp_cbf/cbfSubarray/$$i; done &&\
             /venv/bin/python /app/csplmc/CbfSubarray/CbfSubarray/CbfSubarray.py cbf"

  cbfmaster:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/csplmc:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cbfmaster
    depends_on:
      - cbfsubarray
      - vcc
      - fsp
      - databaseds
      - rsyslog-csplmc
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --check-device mid_csp_cbf/master/main &&\
             /venv/bin/python /app/csplmc/CbfMaster/CbfMaster/CbfMaster.py cbf"

  tmtelstatetest:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/csplmc:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}tmtelstatetest
    depends_on:
      - databaseds
      - rsyslog-csplmc
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --check-device ska1_mid/tm/telmodel &&\
             /venv/bin/python /app/csplmc/TmTelstateTest/TmTelstateTest.py tm"
             
  rsyslog-csplmc:
    image: jumanjiman/rsyslog
    container_name: ${CONTAINER_NAME_PREFIX}rsyslog-csplmc
    network_mode: ${NETWORK_MODE}
