version: "2.2"

services:
  vcc001:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}vcc001
    depends_on:
      - databaseds
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             tango_admin --check-device mid_csp_cbf/vcc_band12/001 &&\
             tango_admin --check-device mid_csp_cbf/vcc_band3/001 &&\
             tango_admin --check-device mid_csp_cbf/vcc_band4/001 &&\
             tango_admin --check-device mid_csp_cbf/vcc_band5/001 &&\
             tango_admin --check-device mid_csp_cbf/vcc_sw1/001 &&\
             tango_admin --check-device mid_csp_cbf/vcc_sw2/001 &&\
             tango_admin --check-device mid_csp_cbf/vcc/001 &&\
             /venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-001"

  vcc002:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}vcc002
    depends_on:
      - databaseds
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             tango_admin --check-device mid_csp_cbf/vcc_band12/002 &&\
             tango_admin --check-device mid_csp_cbf/vcc_band3/002 &&\
             tango_admin --check-device mid_csp_cbf/vcc_band4/002 &&\
             tango_admin --check-device mid_csp_cbf/vcc_band5/002 &&\
             tango_admin --check-device mid_csp_cbf/vcc_sw1/002 &&\
             tango_admin --check-device mid_csp_cbf/vcc_sw2/002 &&\
             tango_admin --check-device mid_csp_cbf/vcc/002 &&\
             /venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-002"

  vcc003:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}vcc003
    depends_on:
      - databaseds
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             tango_admin --check-device mid_csp_cbf/vcc_band12/003 &&\
             tango_admin --check-device mid_csp_cbf/vcc_band3/003 &&\
             tango_admin --check-device mid_csp_cbf/vcc_band4/003 &&\
             tango_admin --check-device mid_csp_cbf/vcc_band5/003 &&\
             tango_admin --check-device mid_csp_cbf/vcc_sw1/003 &&\
             tango_admin --check-device mid_csp_cbf/vcc_sw2/003 &&\
             tango_admin --check-device mid_csp_cbf/vcc/003 &&\
             /venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-003"

  vcc004:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}vcc004
    depends_on:
      - databaseds
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             tango_admin --check-device mid_csp_cbf/vcc_band12/004 &&\
             tango_admin --check-device mid_csp_cbf/vcc_band3/004 &&\
             tango_admin --check-device mid_csp_cbf/vcc_band4/004 &&\
             tango_admin --check-device mid_csp_cbf/vcc_band5/004 &&\
             tango_admin --check-device mid_csp_cbf/vcc_sw1/004 &&\
             tango_admin --check-device mid_csp_cbf/vcc_sw2/004 &&\
             tango_admin --check-device mid_csp_cbf/vcc/004 &&\
             /venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-004"

  fsp01:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}fsp01
    depends_on:
      - vcc001
      - vcc002
      - vcc003
      - vcc004
      - databaseds
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             tango_admin --check-device mid_csp_cbf/fsp_corr/01 &&\
             tango_admin --check-device mid_csp_cbf/fsp_pss/01 &&\
             tango_admin --check-device mid_csp_cbf/fsp_pst/01 &&\
             tango_admin --check-device mid_csp_cbf/fsp_vlbi/01 &&\
             tango_admin --check-device mid_csp_cbf/fspSubarray/01_01 &&\
             tango_admin --check-device mid_csp_cbf/fsp/01 &&\
             /venv/bin/python /app/tangods/Fsp/FspMulti/FspMulti.py fsp-01"

  fsp02:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}fsp02
    depends_on:
      - vcc001
      - vcc002
      - vcc003
      - vcc004
      - databaseds
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             tango_admin --check-device mid_csp_cbf/fsp_corr/02 &&\
             tango_admin --check-device mid_csp_cbf/fsp_pss/02 &&\
             tango_admin --check-device mid_csp_cbf/fsp_pst/02 &&\
             tango_admin --check-device mid_csp_cbf/fsp_vlbi/02 &&\
             tango_admin --check-device mid_csp_cbf/fspSubarray/02_01 &&\
             tango_admin --check-device mid_csp_cbf/fsp/02 &&\
             /venv/bin/python /app/tangods/Fsp/FspMulti/FspMulti.py fsp-02"

  fsp03:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}fsp03
    depends_on:
      - vcc001
      - vcc002
      - vcc003
      - vcc004
      - databaseds
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             tango_admin --check-device mid_csp_cbf/fsp_corr/03 &&\
             tango_admin --check-device mid_csp_cbf/fsp_pss/03 &&\
             tango_admin --check-device mid_csp_cbf/fsp_pst/03 &&\
             tango_admin --check-device mid_csp_cbf/fsp_vlbi/03 &&\
             tango_admin --check-device mid_csp_cbf/fspSubarray/03_01 &&\
             tango_admin --check-device mid_csp_cbf/fsp/03 &&\
             /venv/bin/python /app/tangods/Fsp/FspMulti/FspMulti.py fsp-03"

  fsp04:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}fsp04
    depends_on:
      - vcc001
      - vcc002
      - vcc003
      - vcc004
      - databaseds
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             tango_admin --check-device mid_csp_cbf/fsp_corr/04 &&\
             tango_admin --check-device mid_csp_cbf/fsp_pss/04 &&\
             tango_admin --check-device mid_csp_cbf/fsp_pst/04 &&\
             tango_admin --check-device mid_csp_cbf/fsp_vlbi/04 &&\
             tango_admin --check-device mid_csp_cbf/fspSubarray/04_01 &&\
             tango_admin --check-device mid_csp_cbf/fsp/04 &&\
             /venv/bin/python /app/tangods/Fsp/FspMulti/FspMulti.py fsp-04"

  cbfsubarray01:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cbfsubarray01
    depends_on:
      - vcc001
      - vcc002
      - vcc003
      - vcc004
      - fsp01
      - fsp02
      - fsp03
      - fsp04
      - databaseds
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             tango_admin --check-device mid_csp_cbf/sw1/01 &&\
             tango_admin --check-device mid_csp_cbf/sw2/01 &&\
             tango_admin --check-device mid_csp_cbf/sub_elt/subarray_01 &&\
             /venv/bin/python /app/tangods/CbfSubarray/CbfSubarrayMulti/CbfSubarrayMulti.py cbfSubarray-01"

  cbfmaster:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cbfmaster
    depends_on:
      - vcc001
      - vcc002
      - vcc003
      - vcc004
      - fsp01
      - fsp02
      - fsp03
      - fsp04
      - cbfsubarray01
      - databaseds
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             tango_admin --check-device mid_csp_cbf/sub_elt/master &&\
             /venv/bin/python /app/tangods/CbfMaster/CbfMaster/CbfMaster.py master"

  tmcspsubarrayleafnodetest:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}tmcspsubarrayleafnodetest
    depends_on:
      - cbfmaster
      - databaseds
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             tango_admin --check-device ska_mid/tm_leaf_node/csp_subarray_01 &&\
             /venv/bin/python /app/tangods/TmCspSubarrayLeafNodeTest/TmCspSubarrayLeafNodeTest.py tm"

  rsyslog:
    image: jumanjiman/rsyslog
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}rsyslog
