apiVersion: v2
name: ska-mid-cbf-umbrella
description: An umbrella Helm chart for deploying the whole Mid_CBF prototype.
appVersion: "0.6.6"
version: "0.3.6"
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: ska-tango-base
  version: 0.3.8
  repository:  https://artefact.skao.int/repository/helm-internal
- name: ska-tango-util
  version: 0.3.7
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-mid-cbf-mcs
  version: 0.1.3
  repository: "file://../ska-mid-cbf-mcs"
- name: ska-mid-cbf-tmleafnode
  version: 0.3.6
  repository: "file://../ska-mid-cbf-tmleafnode"
- name: ska-webjive
  version: 1.0.25
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-webjive.enabled
- name: ska-webjive-auth
  version: 0.1.3
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-webjive.enabled
- name: ska-dashboard-repo
  version: 0.1.7
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-webjive.enabled
