display: ":0"
xauthority: "~/.Xauthority"
minikube: true

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  environment_variables: []
  sub-system:
    ska-tango-base:
      enabled: false

ska-tango-base:
  dsconfig:
    timeout: 300s
    image:
        registry: artefact.skao.int
        image: ska-tango-images-tango-dsconfig
        tag: 1.5.11
        pullPolicy: IfNotPresent
  vnc:
    enabled: false
  tangorest:
    enabled: false
  ingress:
    enabled: false
  tangodb:
    use_pv: false

ska-webjive:
    enabled: false
