# Default values for Mid CBF tmleafnode simulator devices.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: csp
subsystem: tmsimulator-mid
telescope: SKA-mid

labels:
  app: ska-mid-cbf-mcs

global:
  minikube: false
  exposeDatabaseDS: true
  exposeAllDS: false
  tango_host: databaseds-tango-base-test:10000

midcbf:
  image:
    registry: artefact.skao.int
    image: ska-mid-cbf-mcs
    tag: 0.10.16
    pullPolicy: IfNotPresent

deviceServers:
  tmcspsubarrayleafnodetest:
    enabled: true
    file: "data/tmcspsubarrayleafnodetest.yaml"

nodeSelector: {}

tolerations: []

affinity: {}
