# Default values for tmleafnode.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
display: ":0"
xauthority: "~/.Xauthority"

system: csp
subsystem: tmsimulator-mid
telescope: SKA-mid

tmleafnodesimulator:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: mid-cbf-mcs
    tag: 0.4.5-2e83f4c
    pullPolicy: IfNotPresent

dsconfig:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-dsconfig
    tag: 1.2.5.1
    pullPolicy: IfNotPresent

deviceServers:
  - name: tmcspsubarrayleafnodetest
    function: simul-observation
    domain: telstate
    args:
      - -c
      - "retry --max=20 -- tango_admin --ping-device mid_csp_cbf/sub_elt/subarray_01 &&\
         /venv/bin/python /app/tangods/TmCspSubarrayLeafNodeTest/TmCspSubarrayLeafNodeTest.py tm"
  - name: tmcspsubarrayleafnodetest2
    function: simul-observation
    domain: telstate
    args:
      - -c
      - "retry --max=20 -- tango_admin --ping-device mid_csp_cbf/sub_elt/subarray_02 &&\
         /venv/bin/python /app/tangods/TmCspSubarrayLeafNodeTest/TmCspSubarrayLeafNodeTest.py tm2"

nodeSelector: {}

tolerations: []

affinity: {}

resources:
  requests:
    cpu: 100m     # 100m = 0.10 CPU
    memory: 128Mi # 128Mi = 0.12 GB mem
  limits:
    cpu: 200m     # 200m = 0.20 CPU
    memory: 256Mi # 256Mi = 0.25 GB mem
