# Default values for ska-mid-cbf HELM chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: csp
subsystem: cbfmcs-mid
telescope: SKA-mid

global:
  minikube: true
  exposeDatabaseDS: true
  exposeAllDS: true
  tango_host: databaseds-tango-base-test:10000
  labels:
    app: ska-mid-cbf-mcs
annotations:
    app.gitlab.com/app: CI_PROJECT_PATH_SLUG
    app.gitlab.com/env: CI_ENVIRONMENT_SLUG  
dsconfig:
    configuration_file: data/midcbfconfig.json
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.1
      pullPolicy: IfNotPresent
itango:
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-itango
      tag: 9.3.5
      pullPolicy: IfNotPresent 

midcbf:
  image:
    registry: artefact.skao.int
    image: ska-mid-cbf-mcs
    tag: 0.5.6
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 200m
    memory: 256Mi
    ephemeral-storage: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi  
    ephemeral-storage: 256Mi

deviceServers:
  - name: cbfcontroller
    function: cbf-central-control
    domain: csp-monitoring
    command: "CbfController"
    instances: ["controller"]
    depends_on:
      - device: mid_csp_cbf/vcc/001   
      - device: mid_csp_cbf/vcc/002  
      - device: mid_csp_cbf/vcc/003  
      - device: mid_csp_cbf/vcc/004  
      - device: mid_csp_cbf/fsp/01 
      - device: mid_csp_cbf/fsp/02 
      - device: mid_csp_cbf/fsp/03 
      - device: mid_csp_cbf/fsp/04
      - device: mid_csp_cbf/talon_lru/001
      - device: mid_csp_cbf/talon_lru/002
    server:
      name: "CbfController"
      instances:
      - name: "controller"
        classes:
        - name: "CbfController"
          devices:
          - name: "mid_csp_cbf/sub_elt/controller"
    image:
      registry: "{{.Values.midcbf.image.registry}}"
      image: "{{.Values.midcbf.image.image}}"
      tag: "{{.Values.midcbf.image.tag}}"
      pullPolicy: "{{.Values.midcbf.image.pullPolicy}}"
  - name: cbfsubarray
    function: cbf-subarray-observation
    domain: subarray
    command: "CbfSubarray"
    instances: ["cbfsubarray-01", "cbfsubarray-02", "cbfsubarray-03"]
    depends_on:
      - device: mid_csp_cbf/sub_elt/controller
    server:
      name: "CbfSubarray"
      instances:
      - name: "cbfsubarray-01"
        classes:
        - name: "CbfSubarray"
          devices:
          - name: "mid_csp_cbf/sub_elt/subarray_01"
      - name: "cbfsubarray-02"
        classes:
        - name: "CbfSubarray"
          devices:
          - name: "mid_csp_cbf/sub_elt/subarray_02"
      - name: "cbfsubarray-03"
        classes:
        - name: "CbfSubarray"
          devices:
          - name: "mid_csp_cbf/sub_elt/subarray_03"
    image:
      registry: "{{.Values.midcbf.image.registry}}"
      image: "{{.Values.midcbf.image.image}}"
      tag: "{{.Values.midcbf.image.tag}}"
      pullPolicy: "{{.Values.midcbf.image.pullPolicy}}"
  - name: vcc
    function: coarse-channelisation
    domain: sensing
    command: "VccMulti"
    instances: ["vcc-001", "vcc-002", "vcc-003", "vcc-004"]
    depends_on:
      - device: sys/database/2
    server:
      name: "VccMulti"
      instances:
      - name: "vcc-001"
        classes:
        - name: "Vcc"
          devices:
          - name: "mid_csp_cbf/vcc/001"
        - name: "VccSearchWindow"
          devices:
          - name: "mid_csp_cbf/vcc_sw1/001"
          - name: "mid_csp_cbf/vcc_sw2/001"
      - name: "vcc-002"
        classes:
        - name: "Vcc"
          devices:
          - name: "mid_csp_cbf/vcc/002"
        - name: "VccSearchWindow"
          devices:
          - name: "mid_csp_cbf/vcc_sw1/002"
          - name: "mid_csp_cbf/vcc_sw2/002"
      - name: "vcc-003"
        classes:
        - name: "Vcc"
          devices:
          - name: "mid_csp_cbf/vcc/003"
        - name: "VccSearchWindow"
          devices:
          - name: "mid_csp_cbf/vcc_sw1/003"
          - name: "mid_csp_cbf/vcc_sw2/003"
      - name: "vcc-004"
        classes:
        - name: "Vcc"
          devices:
          - name: "mid_csp_cbf/vcc/004"
        - name: "VccSearchWindow"
          devices:
          - name: "mid_csp_cbf/vcc_sw1/004"
          - name: "mid_csp_cbf/vcc_sw2/004"
    image:
      registry: "{{.Values.midcbf.image.registry}}"
      image: "{{.Values.midcbf.image.image}}"
      tag: "{{.Values.midcbf.image.tag}}"
      pullPolicy: "{{.Values.midcbf.image.pullPolicy}}"
  - name: fsp
    function: fsp-processing
    domain: signal-processing
    command: "FspMulti"
    instances: ["fsp-01", "fsp-02", "fsp-03", "fsp-04"]
    depends_on:
      - device: mid_csp_cbf/vcc/001
      - device: mid_csp_cbf/vcc/002
      - device: mid_csp_cbf/vcc/003
      - device: mid_csp_cbf/vcc/004
    server:
      name: "FspMulti"
      instances:
      - name: "fsp-01"
        classes:
        - name: "Fsp"
          devices:
          - name: "mid_csp_cbf/fsp/01"
        - name: "FspCorr"
          devices:
          - name: "mid_csp_cbf/fsp_corr/01"
        - name: "FspPss"
          devices:
          - name: "mid_csp_cbf/fsp_pss/01"
        - name: "FspPst"
          devices:
          - name: "mid_csp_cbf/fsp_pst/01"
        - name: "FspVlbi"
          devices:
          - name: "mid_csp_cbf/fsp_vlbi/01"
        - name: "FspCorrSubarray"
          devices:
          - name: "mid_csp_cbf/fspCorrSubarray/01_01"
          - name: "mid_csp_cbf/fspCorrSubarray/01_02"
          - name: "mid_csp_cbf/fspCorrSubarray/01_03"
        - name: "FspPssSubarray"
          devices:
          - name: "mid_csp_cbf/fspPssSubarray/01_01"
          - name: "mid_csp_cbf/fspPssSubarray/01_02"
          - name: "mid_csp_cbf/fspPssSubarray/01_03"
        - name: "FspPstSubarray"
          devices:
          - name: "mid_csp_cbf/fspPstSubarray/01_01"
          - name: "mid_csp_cbf/fspPstSubarray/01_02"
          - name: "mid_csp_cbf/fspPstSubarray/01_03"
      - name: "fsp-02"
        classes:
        - name: "Fsp"
          devices:
          - name: "mid_csp_cbf/fsp/02"
        - name: "FspCorr"
          devices:
          - name: "mid_csp_cbf/fsp_corr/02"
        - name: "FspPss"
          devices:
          - name: "mid_csp_cbf/fsp_pss/02"
        - name: "FspPst"
          devices:
          - name: "mid_csp_cbf/fsp_pst/02"
        - name: "FspVlbi"
          devices:
          - name: "mid_csp_cbf/fsp_vlbi/02"
        - name: "FspCorrSubarray"
          devices:
          - name: "mid_csp_cbf/fspCorrSubarray/02_01"
          - name: "mid_csp_cbf/fspCorrSubarray/02_02"
          - name: "mid_csp_cbf/fspCorrSubarray/02_03"
        - name: "FspPssSubarray"
          devices:
          - name: "mid_csp_cbf/fspPssSubarray/02_01"
          - name: "mid_csp_cbf/fspPssSubarray/02_02"
          - name: "mid_csp_cbf/fspPssSubarray/02_03"
        - name: "FspPstSubarray"
          devices:
          - name: "mid_csp_cbf/fspPstSubarray/02_01"
          - name: "mid_csp_cbf/fspPstSubarray/02_02"
          - name: "mid_csp_cbf/fspPstSubarray/02_03"
      - name: "fsp-03"
        classes:
        - name: "Fsp"
          devices:
          - name: "mid_csp_cbf/fsp/03"
        - name: "FspCorr"
          devices:
          - name: "mid_csp_cbf/fsp_corr/03"
        - name: "FspPss"
          devices:
          - name: "mid_csp_cbf/fsp_pss/03"
        - name: "FspPst"
          devices:
          - name: "mid_csp_cbf/fsp_pst/03"
        - name: "FspVlbi"
          devices:
          - name: "mid_csp_cbf/fsp_vlbi/03"
        - name: "FspCorrSubarray"
          devices:
          - name: "mid_csp_cbf/fspCorrSubarray/03_01"
          - name: "mid_csp_cbf/fspCorrSubarray/03_02"
          - name: "mid_csp_cbf/fspCorrSubarray/03_03"
        - name: "FspPssSubarray"
          devices:
          - name: "mid_csp_cbf/fspPssSubarray/03_01"
          - name: "mid_csp_cbf/fspPssSubarray/03_02"
          - name: "mid_csp_cbf/fspPssSubarray/03_03"
        - name: "FspPstSubarray"
          devices:
          - name: "mid_csp_cbf/fspPstSubarray/03_01"
          - name: "mid_csp_cbf/fspPstSubarray/03_02"
          - name: "mid_csp_cbf/fspPstSubarray/03_03"
      - name: "fsp-04"
        classes:
        - name: "Fsp"
          devices:
          - name: "mid_csp_cbf/fsp/04"
        - name: "FspCorr"
          devices:
          - name: "mid_csp_cbf/fsp_corr/04"
        - name: "FspPss"
          devices:
          - name: "mid_csp_cbf/fsp_pss/04"
        - name: "FspPst"
          devices:
          - name: "mid_csp_cbf/fsp_pst/04"
        - name: "FspVlbi"
          devices:
          - name: "mid_csp_cbf/fsp_vlbi/04"
        - name: "FspCorrSubarray"
          devices:
          - name: "mid_csp_cbf/fspCorrSubarray/04_01"
          - name: "mid_csp_cbf/fspCorrSubarray/04_02"
          - name: "mid_csp_cbf/fspCorrSubarray/04_03"
        - name: "FspPssSubarray"
          devices:
          - name: "mid_csp_cbf/fspPssSubarray/04_01"
          - name: "mid_csp_cbf/fspPssSubarray/04_02"
          - name: "mid_csp_cbf/fspPssSubarray/04_03"
        - name: "FspPstSubarray"
          devices:
          - name: "mid_csp_cbf/fspPstSubarray/04_01"
          - name: "mid_csp_cbf/fspPstSubarray/04_02"
          - name: "mid_csp_cbf/fspPstSubarray/04_03"
    image:
      registry: "{{.Values.midcbf.image.registry}}"
      image: "{{.Values.midcbf.image.image}}"
      tag: "{{.Values.midcbf.image.tag}}"
      pullPolicy: "{{.Values.midcbf.image.pullPolicy}}"
  - name: powerswitch
    function: power-switch
    domain: mid-csp-cbf
    command: "PowerSwitch"
    instances: ["powerswitch-001"]
    server:
      name: "PowerSwitch"
      instances:
      - name: "powerswitch-001"
        classes:
        - name: "PowerSwitch"
          devices:
          - name: "mid_csp_cbf/power_switch/001"
    image:
      registry: "{{.Values.midcbf.image.registry}}"
      image: "{{.Values.midcbf.image.image}}"
      tag: "{{.Values.midcbf.image.tag}}"
      pullPolicy: "{{.Values.midcbf.image.pullPolicy}}"
  - name: talonlru
    function: talon-lru
    domain: mid-csp-cbf
    command: "TalonLRU"
    instances: ["talonlru-001", "talonlru-002"]
    depends_on:
      - device: mid_csp_cbf/power_switch/001
    server:
      name: "TalonLRU"
      instances:
      - name: "talonlru-001"
        classes:
        - name: "TalonLRU"
          devices:
          - name: "mid_csp_cbf/talon_lru/001"
      - name: "talonlru-002"
        classes:
        - name: "TalonLRU"
          devices:
          - name: "mid_csp_cbf/talon_lru/002"
    image:
      registry: "{{.Values.midcbf.image.registry}}"
      image: "{{.Values.midcbf.image.image}}"
      tag: "{{.Values.midcbf.image.tag}}"
      pullPolicy: "{{.Values.midcbf.image.pullPolicy}}"

nodeSelector: {}

affinity: {}

tolerations: []

