links_to_fsp1:
  - talondx-001/slim-tx-rx/tx0 -> talondx-001/slim-tx-rx/rx0
  - talondx-002/slim-tx-rx/tx0 -> talondx-001/slim-tx-rx/rx1
  - talondx-003/slim-tx-rx/tx0 -> talondx-001/slim-tx-rx/rx2
  - talondx-004/slim-tx-rx/tx0 -> talondx-001/slim-tx-rx/rx3
  - talondx-005/slim-tx-rx/tx0 -> talondx-001/slim-tx-rx/rx4 [x]
  - talondx-006/slim-tx-rx/tx0 -> talondx-001/slim-tx-rx/rx5 [x]
  - talondx-007/slim-tx-rx/tx0 -> talondx-001/slim-tx-rx/rx6 [x]
  - talondx-008/slim-tx-rx/tx0 -> talondx-001/slim-tx-rx/rx7 [x]