{{ $localchart := . }}

{{ template "ska-tango-util.configuration.tpl" . }}

{{ range $deviceserver := .Values.deviceServers }}

  {{ if $deviceserver.expose }}

    {{ $context := dict "deviceserver" $deviceserver "image" $deviceserver.image "local" $localchart }}
    {{ template "ska-tango-util.multidevice-config.tpl" $context }}
    {{ template "ska-tango-util.multidevice-sacc-role.tpl" $context }}
    {{ template "ska-tango-util.multidevice-job.tpl" $context }}
    {{ template "ska-tango-util.multidevice-svc.tpl" $context }}

  {{ else }}

    {{ range $instance := $deviceserver.instances }}

      {{ $context := dict "deviceserver" $deviceserver "image" $deviceserver.image "local" $localchart "instance" $instance  }}
      {{ template "ska-tango-util.deviceserver.tpl" $context }}
    
    {{ end }} ## instances
  {{ end }}
{{ end }} # deviceservers