links_to_fsp1:
  - talondx-001/slim-tx-rx/tx-fs0 -> talondx-001/slim-tx-rx/rx-fs0 [x]
  - talondx-002/slim-tx-rx/tx-fs0 -> talondx-001/slim-tx-rx/rx-fs1 [x]
  - talondx-003/slim-tx-rx/tx-fs0 -> talondx-001/slim-tx-rx/rx-fs2 [x]
  - talondx-004/slim-tx-rx/tx-fs0 -> talondx-001/slim-tx-rx/rx-fs3 [x]
  - talondx-005/slim-tx-rx/tx-fs0 -> talondx-001/slim-tx-rx/rx-fs4 [x]
  - talondx-006/slim-tx-rx/tx-fs0 -> talondx-001/slim-tx-rx/rx-fs5 [x]
  - talondx-007/slim-tx-rx/tx-fs0 -> talondx-001/slim-tx-rx/rx-fs6 [x]
  - talondx-008/slim-tx-rx/tx-fs0 -> talondx-001/slim-tx-rx/rx-fs7 [x]
links_to_fsp2:
  - talondx-001/slim-tx-rx/tx-fs1 -> talondx-002/slim-tx-rx/rx-fs0 [x]
  - talondx-002/slim-tx-rx/tx-fs1 -> talondx-002/slim-tx-rx/rx-fs1 [x]
  - talondx-003/slim-tx-rx/tx-fs1 -> talondx-002/slim-tx-rx/rx-fs2 [x]
  - talondx-004/slim-tx-rx/tx-fs1 -> talondx-002/slim-tx-rx/rx-fs3 [x]
  - talondx-005/slim-tx-rx/tx-fs1 -> talondx-002/slim-tx-rx/rx-fs4 [x]
  - talondx-006/slim-tx-rx/tx-fs1 -> talondx-002/slim-tx-rx/rx-fs5 [x]
  - talondx-007/slim-tx-rx/tx-fs1 -> talondx-002/slim-tx-rx/rx-fs6 [x]
  - talondx-008/slim-tx-rx/tx-fs1 -> talondx-002/slim-tx-rx/rx-fs7 [x]
links_to_fsp3:
  - talondx-001/slim-tx-rx/tx-fs2 -> talondx-003/slim-tx-rx/rx-fs0 [x]
  - talondx-002/slim-tx-rx/tx-fs2 -> talondx-003/slim-tx-rx/rx-fs1 [x]
  - talondx-003/slim-tx-rx/tx-fs2 -> talondx-003/slim-tx-rx/rx-fs2 [x]
  - talondx-004/slim-tx-rx/tx-fs2 -> talondx-003/slim-tx-rx/rx-fs3 [x]
  - talondx-005/slim-tx-rx/tx-fs2 -> talondx-003/slim-tx-rx/rx-fs4 [x]
  - talondx-006/slim-tx-rx/tx-fs2 -> talondx-003/slim-tx-rx/rx-fs5 [x]
  - talondx-007/slim-tx-rx/tx-fs2 -> talondx-003/slim-tx-rx/rx-fs6 [x]
  - talondx-008/slim-tx-rx/tx-fs2 -> talondx-003/slim-tx-rx/rx-fs7 [x]
links_to_fsp4:
  - talondx-001/slim-tx-rx/tx-fs3 -> talondx-004/slim-tx-rx/rx-fs0 [x]
  - talondx-002/slim-tx-rx/tx-fs3 -> talondx-004/slim-tx-rx/rx-fs1 [x]
  - talondx-003/slim-tx-rx/tx-fs3 -> talondx-004/slim-tx-rx/rx-fs2 [x]
  - talondx-004/slim-tx-rx/tx-fs3 -> talondx-004/slim-tx-rx/rx-fs3 [x]
  - talondx-005/slim-tx-rx/tx-fs3 -> talondx-004/slim-tx-rx/rx-fs4 [x]
  - talondx-006/slim-tx-rx/tx-fs3 -> talondx-004/slim-tx-rx/rx-fs5 [x]
  - talondx-007/slim-tx-rx/tx-fs3 -> talondx-004/slim-tx-rx/rx-fs6 [x]
  - talondx-008/slim-tx-rx/tx-fs3 -> talondx-004/slim-tx-rx/rx-fs7 [x]
links_to_fsp5:
  - talondx-001/slim-tx-rx/tx-fs4 -> talondx-005/slim-tx-rx/rx-fs0 [x]
  - talondx-002/slim-tx-rx/tx-fs4 -> talondx-005/slim-tx-rx/rx-fs1 [x]
  - talondx-003/slim-tx-rx/tx-fs4 -> talondx-005/slim-tx-rx/rx-fs2 [x]
  - talondx-004/slim-tx-rx/tx-fs4 -> talondx-005/slim-tx-rx/rx-fs3 [x]
  - talondx-005/slim-tx-rx/tx-fs4 -> talondx-005/slim-tx-rx/rx-fs4 [x]
  - talondx-006/slim-tx-rx/tx-fs4 -> talondx-005/slim-tx-rx/rx-fs5 [x]
  - talondx-007/slim-tx-rx/tx-fs4 -> talondx-005/slim-tx-rx/rx-fs6 [x]
  - talondx-008/slim-tx-rx/tx-fs4 -> talondx-005/slim-tx-rx/rx-fs7 [x]
links_to_fsp6:
  - talondx-001/slim-tx-rx/tx-fs5 -> talondx-006/slim-tx-rx/rx-fs0 [x]
  - talondx-002/slim-tx-rx/tx-fs5 -> talondx-006/slim-tx-rx/rx-fs1 [x]
  - talondx-003/slim-tx-rx/tx-fs5 -> talondx-006/slim-tx-rx/rx-fs2 [x]
  - talondx-004/slim-tx-rx/tx-fs5 -> talondx-006/slim-tx-rx/rx-fs3 [x]
  - talondx-005/slim-tx-rx/tx-fs5 -> talondx-006/slim-tx-rx/rx-fs4 [x]
  - talondx-006/slim-tx-rx/tx-fs5 -> talondx-006/slim-tx-rx/rx-fs5 [x]
  - talondx-007/slim-tx-rx/tx-fs5 -> talondx-006/slim-tx-rx/rx-fs6 [x]
  - talondx-008/slim-tx-rx/tx-fs5 -> talondx-006/slim-tx-rx/rx-fs7 [x]
links_to_fsp7:
  - talondx-001/slim-tx-rx/tx-fs6 -> talondx-007/slim-tx-rx/rx-fs0 [x]
  - talondx-002/slim-tx-rx/tx-fs6 -> talondx-007/slim-tx-rx/rx-fs1 [x]
  - talondx-003/slim-tx-rx/tx-fs6 -> talondx-007/slim-tx-rx/rx-fs2 [x]
  - talondx-004/slim-tx-rx/tx-fs6 -> talondx-007/slim-tx-rx/rx-fs3 [x]
  - talondx-005/slim-tx-rx/tx-fs6 -> talondx-007/slim-tx-rx/rx-fs4 [x]
  - talondx-006/slim-tx-rx/tx-fs6 -> talondx-007/slim-tx-rx/rx-fs5 [x]
  - talondx-007/slim-tx-rx/tx-fs6 -> talondx-007/slim-tx-rx/rx-fs6 [x]
  - talondx-008/slim-tx-rx/tx-fs6 -> talondx-007/slim-tx-rx/rx-fs7 [x]
links_to_fsp8:
  - talondx-001/slim-tx-rx/tx-fs7 -> talondx-008/slim-tx-rx/rx-fs0 [x]
  - talondx-002/slim-tx-rx/tx-fs7 -> talondx-008/slim-tx-rx/rx-fs1 [x]
  - talondx-003/slim-tx-rx/tx-fs7 -> talondx-008/slim-tx-rx/rx-fs2 [x]
  - talondx-004/slim-tx-rx/tx-fs7 -> talondx-008/slim-tx-rx/rx-fs3 [x]
  - talondx-005/slim-tx-rx/tx-fs7 -> talondx-008/slim-tx-rx/rx-fs4 [x]
  - talondx-006/slim-tx-rx/tx-fs7 -> talondx-008/slim-tx-rx/rx-fs5 [x]
  - talondx-007/slim-tx-rx/tx-fs7 -> talondx-008/slim-tx-rx/rx-fs6 [x]
  - talondx-008/slim-tx-rx/tx-fs7 -> talondx-008/slim-tx-rx/rx-fs7 [x]