links_to_vis1:
  - talondx-001/slim-tx-rx/tx-vis0 -> talondx-001/slim-tx-rx/rx-vis0 [x]
  - talondx-002/slim-tx-rx/tx-vis0 -> talondx-001/slim-tx-rx/rx-vis1 [x]
  - talondx-003/slim-tx-rx/tx-vis0 -> talondx-001/slim-tx-rx/rx-vis2 [x]
  - talondx-004/slim-tx-rx/tx-vis0 -> talondx-001/slim-tx-rx/rx-vis3 [x]
  - talondx-005/slim-tx-rx/tx-vis0 -> talondx-001/slim-tx-rx/rx-vis4 [x]
  - talondx-006/slim-tx-rx/tx-vis0 -> talondx-008/slim-tx-rx/rx-vis0 [x]
  - talondx-007/slim-tx-rx/tx-vis0 -> talondx-001/slim-tx-rx/rx-vis1 [x]
  - talondx-008/slim-tx-rx/tx-vis0 -> talondx-008/slim-tx-rx/rx-vis2 [x]