talon_ip:
    "001": 192.168.8.1
    "002": 192.168.8.2
    "003": 192.168.8.3
    "004": 192.168.8.4
    "005": 192.168.8.5
    "006": 192.168.8.6
    "007": 192.168.8.7
    "008": 192.168.8.8
talon_LRU:
- "001":
    PDU1Address: "mid_csp_cbf/power_switch/001"
    PDU1PowerOutlet: "0"
    PDU2Address: "mid_csp_cbf/power_switch/002"
    PDU2PowerOutlet: "AA1"
    TalonDxBoard1Address: "mid_csp_cbf/talon_board/001"
    TalonDxBoard2Address: "mid_csp_cbf/talon_board/002"
- "002":
    PDU1Address: "mid_csp_cbf/power_switch/001"
    PDU1PowerOutlet: "1"
    PDU2Address: "mid_csp_cbf/power_switch/001"
    PDU2PowerOutlet: "1"
    TalonDxBoard1Address: "mid_csp_cbf/talon_board/003"
    TalonDxBoard2Address: "mid_csp_cbf/talon_board/004"
- "003":
    PDU1Address: "mid_csp_cbf/power_switch/001"
    PDU1PowerOutlet: "2"
    PDU2Address: "mid_csp_cbf/power_switch/001"
    PDU2PowerOutlet: "2"
    TalonDxBoard1Address: "mid_csp_cbf/talon_board/005"
    TalonDxBoard2Address: "mid_csp_cbf/talon_board/006"
- "004":
    PDU1Address: "mid_csp_cbf/power_switch/001"
    PDU1PowerOutlet: "3"
    PDU2Address: "001"
    PDU2PowerOutlet: "3"
    TalonDxBoard1Address: "mid_csp_cbf/talon_board/007"
    TalonDxBoard2Address: "mid_csp_cbf/talon_board/008"
power_switch:
- "001":
    PowerSwitchProtocol: "http"
    PowerSwitchIp: "192.168.0.100"
    PowerSwitchLogin: "admin"
    PowerSwitchPassword: "1234"
    PowerSwitchRequestHeaderContentType: "application/x-www-form-urlencoded"
    PowerSwitchOutletListUrl: "restapi/relay/outlets/"
    PowerSwitchOutletStateUrl: "restapi/relay/outlets/{outlet}/"
    PowerSwitchOutletControlUrl: "restapi/relay/outlets/{outlet}/state/"
    PowerSwitchTurnOnAction: "value=true"
    PowerSwitchTurnOffAction: "value=false"
    PowerSwitchOutletStateOn: "True"
    PowerSwitchOutletStateOff: "False"
    PowerSwitchOutletSchemaFile: "charts/ska-mid-cbf-mcs/data/power_switch_001_schema.json"
    PowerSwitchOutletIdList:
    - "0"
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"
    - "6"
    - "7"
- "002":
    PowerSwitchProtocol: "https"
    PowerSwitchIp: "192.168.1.254"
    PowerSwitchLogin: "admn"
    PowerSwitchPassword: "admn-1-Psi"
    PowerSwitchRequestHeaderContentType: "application/json"
    PowerSwitchOutletListUrl: "jaws/monitor/outlets"
    PowerSwitchOutletStateUrl: "jaws/monitor/outlets/{outlet}"
    PowerSwitchOutletControlUrl: "jaws/control/outlets/{outlet}"
    PowerSwitchTurnOnAction: '{\"control_action\": \"on\"}'
    PowerSwitchTurnOffAction: '{\"control_action\": \"off\"}'
    PowerSwitchOutletStateOn: "On"
    PowerSwitchOutletStateOff: "Off"
    PowerSwitchOutletSchemaFile: "charts/ska-mid-cbf-mcs/data/power_switch_002_schema.json"
    PowerSwitchOutletIdList:
    - "AA1"
    - "AA2"
    - "AA3"
    - "AA4"
    - "AA5"
    - "AA6"
    - "AA7"
    - "AA8"
    - "AA9"
    - "AA10"
    - "AA11"
    - "AA12"
    - "AA13"
    - "AA14"
    - "AA15"
    - "AA16"
    - "AA17"
    - "AA18"
    - "AA19"
    - "AA20"
    - "AA21"
    - "AA22"
    - "AA23"
    - "AA24"
    - "AA25"
    - "AA26"
    - "AA27"
    - "AA28"
    - "AA29"
    - "AA30"
    - "AA31"
    - "AA32"
    - "AA33"
    - "AA34"
    - "AA35"
    - "AA36"
    - "AA37"
    - "AA38"
    - "AA39"
    - "AA40"
    - "AA41"
    - "AA42"
    - "AA43"
    - "AA44"
    - "AA45"
    - "AA46"
    - "AA47"
    - "AA48"