apiVersion: v1
kind: Pod
metadata:
  name: engineering-console-deployer
spec:
  volumes:
    - name: artifacts-pv-storage
      persistentVolumeClaim:
        claimName: artifacts-pvc-{{ .Release.Name }} 
  containers:
  - name: engineering-console-deployer-cont
    image: artefact.skao.int/ska-mid-cbf-engineering-console-deployer:{{ .Values.engineeringConsoleVersion }}
    env:
      - name: RAW_USER_ACCOUNT
        value: 
      - name: RAW_USER_PASS
        value: 
      - name: TANGO_HOST
        value: {{ .Values.global.tango_host }}
    command: ["/bin/bash","-c"]
    args: ["tail -f /dev/null"]
    volumeMounts:
      - mountPath: "/app/images/ska-mid-cbf-engineering-console/artifacts"
        name: artifacts-pv-storage

