# Default values for ska-mid-cbf HELM chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: csp
subsystem: cbfmcs-mid
telescope: SKA-mid
engineeringConsoleVersion: 0.10.6
signalVerificationVersion: 0.2.16

labels:
  app: ska-mid-cbf-mcs

global:
  minikube: false
  exposeDatabaseDS: true
  exposeAllDS: false
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.12
      pullPolicy: IfNotPresent

midcbf:
  image:
    registry: artefact.skao.int
    image: ska-mid-cbf-mcs
    tag: 0.14.2
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 200m
    memory: 256Mi
    ephemeral-storage: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi  
    ephemeral-storage: 256Mi

deviceServers:
  cbfcontroller:
    enabled: true
    file: "data/cbfcontroller.yaml"

  cbfsubarray:
    enabled: true
    file: "data/cbfsubarray.yaml"

  vcc:
    enabled: true
    file: "data/vcc.yaml"
  
  fsp:
    enabled: true
    file: "data/fsp.yaml"
  
  powerswitch:
    file: "data/powerswitch.yaml"

  talonlru:
    enabled: true
    file: "data/talonlru.yaml"

  talonboard:
    enabled: true
    file: "data/talonboard.yaml"

  slim:
    enabled: true
    file: "data/slim.yaml"

  slimlink:
    enabled: true
    file: "data/slimlink.yaml"

  talondxlogconsumer:
    enabled: true
    file: "data/talondxlogconsumer.yaml"

ska-mid-cbf-engineering-console:
  enabled: true
# Uncomment the section below to use custom Engineering Console image
  engineeringconsole:
    image:
      registry: registry.gitlab.com/ska-telescope/ska-mid-cbf-engineering-console
      image: ska-mid-cbf-engineering-console
      tag: 0.10.6-dev.cccc43d28
      pullPolicy: IfNotPresent

nodeSelector: {}

affinity: {}

tolerations: []

hostInfo:
  environment: "minikube"
  hostIP: "127.0.0.1"
  externalPort: 10001
  clusterDomain: cluster.local
