apiVersion: v2
name: mid-cbf-umbrella
description: An umbrella Helm chart for deploying the whole Mid_CBF prototype.
appVersion: 0.4.7
version: 0.1.4

icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: tango-base
  version: 0.2.7
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: mid-cbf
  version: 0.1.3
  repository: "file://../mid-cbf"
- name: mid-cbf-tmleafnode
  version: 0.1.1
  repository: "file://../mid-cbf-tmleafnode"
- name: webjive
  version: 1.0.11
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: webjive-auth
  version: 0.1.0
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: webjive-dashboard
  version: 0.1.0
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
