display: ":0"
xauthority: "~/.Xauthority"
minikube: true

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  environment_variables: []
  sub-system:
    tango-base:
      enabled: false

tango-base:
  vnc:
    enabled: false
  tangorest:
    enabled: false
  ingress:
    enabled: false
  tangodb:
    use_pv: false
