{{ $localchart := . }}

{{ range $key, $deviceserver := .Values.deviceServers_tm }}

{{- $filedeviceserver := tpl ($.Files.Get $deviceserver.file) $ | fromYaml }}

{{ $context := dict "name" $key "deviceserver" $filedeviceserver "image" $deviceserver.image "local" $localchart }}

{{ template "ska-tango-util.multidevice-config.tpl" $context }}

{{ template "ska-tango-util.multidevice-sacc-role.tpl" $context }}

{{ template "ska-tango-util.multidevice-job.tpl" $context }}

{{ template "ska-tango-util.multidevice-svc.tpl" $context }}

{{- $volume_context := dict "volume" $filedeviceserver.volume "local" $localchart }}

{{ end }} # deviceservers

